// Code generated by mockery v2.38.0. DO NOT EDIT.

package processor

import mock "github.com/stretchr/testify/mock"

// MockSupplier is an autogenerated mock type for the Supplier type
type MockSupplier[T interface{}] struct {
	mock.Mock
}

type MockSupplier_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockSupplier[T]) EXPECT() *MockSupplier_Expecter[T] {
	return &MockSupplier_Expecter[T]{mock: &_m.Mock}
}

// FetchNextBatch provides a mock function with given fields:
func (_m *MockSupplier[T]) FetchNextBatch() ([]*T, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchNextBatch")
	}

	var r0 []*T
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*T, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*T)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupplier_FetchNextBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNextBatch'
type MockSupplier_FetchNextBatch_Call[T interface{}] struct {
	*mock.Call
}

// FetchNextBatch is a helper method to define mock.On call
func (_e *MockSupplier_Expecter[T]) FetchNextBatch() *MockSupplier_FetchNextBatch_Call[T] {
	return &MockSupplier_FetchNextBatch_Call[T]{Call: _e.mock.On("FetchNextBatch")}
}

func (_c *MockSupplier_FetchNextBatch_Call[T]) Run(run func()) *MockSupplier_FetchNextBatch_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSupplier_FetchNextBatch_Call[T]) Return(_a0 []*T, _a1 error) *MockSupplier_FetchNextBatch_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupplier_FetchNextBatch_Call[T]) RunAndReturn(run func() ([]*T, error)) *MockSupplier_FetchNextBatch_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockSupplier creates a new instance of MockSupplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplier[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplier[T] {
	mock := &MockSupplier[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
